modLoader="javafml"
loaderVersion="[31,)"
license="MIT (Expat) License"
issueTrackerURL="https://github.com/Geolykt/CraftIRC/issues"
[[mods]]
modId="forgeirc"
version="${version}"
displayName="ForgeIRC"
# A URL to query for updates for this mod. See the JSON update specification <here>
# TODO add 
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
#credits=""
authors="Mbaxter, Geolykt"
description='''
ForgeIRC - A Forge - IRC Bridge

ForgeIRC is a reimplementation of MinestomIRC, which is a fork of CraftIRC 4Sponge, which is a reimplementation of CraftIRC 4.

'''

[[dependencies.forgeirc]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="SERVER"
[[dependencies.forgeirc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="SERVER"
