bots:
  - host: localhost
    user: CraftIRC
    nick: Minestom
    realname: "CraftIRC Bot"
    name: INTERN # this is only used for internal lookup so should be unique for each bot
    channel: "#craftirc" # the IRC channel to listen and send messages to
    ssl: false
    port: 6667
    password: null
    bind:
      host: null
      port: 0
    auth:
      user: null
      pass: null
      nickless: false

    debug-output:
      exceptions: false
      input: false
      output: false
    event:
      # IRC Joins
      irc-join: true
      # Called when a user parts an IRC channel
      irc-quit: true
      # Called when a user is kicked from an IRC channel
      irc-kick: true
      # IRC Chatter
      irc-chat: true
      # (NOT IMPLEMENTED) Called when a user is marked as being away (usually performed via the /away command)
      irc-away: true
      # (NOT IMPLEMENTED) Prints the (minecraft) world time when the ctcp TIME command is sent to the bot
      irc-ctcp-time: true

      # Minecraft chatter
      mc-chat: true
      mc-join: true
      mc-quit: true
    format:
      # Format seen in Minecraft when a user joined in IRC
      # Note: We are using Minestom-style color codes, bukkit-plugin-style color codes (like "&4") aren't going to work
      mc-join: "{#dark_red}*{#red}IRC {#yellow}${user} joined."
      mc-quit: "{#dark_red}*{#red}IRC {#yellow}${user} left (${msg})." # called when a user parts the IRC channel
      mc-kick: "{#dark_red}*{#red}IRC {#yellow}${user} was kicked (${msg})."
      mc-chat: "{#dark_red}*{#red}IRC {#white}<${user}>: ${msg}"
      mc-away: "{#dark_red}*{#red}IRC {#yellow}${user} is now away (${msg})."
      # Format seen in IRC when a player joined in Minecraft
      # Note: the color codes are in mIRC's specification (https://www.mirc.com/colors.html)
      irc-join: "\u00037${user} joined."
      irc-quit: "\u00037${user} left."
      irc-chat: "\u00037${user}:\u0003 ${msg}"
    processors:
      colors-irc: true # Converts MC/Minestom colors into IRC Colors
      colors-mc: true # Converts IRC colors into Minestom colors.
